[package]
authors = ["Joseph T Lyons <JosephTLyons@gmail.com>"]
description = "A periodic table of elements plugin for Nushell"
edition = "2021"
license = "GPL-3.0-only"
name = "nu_plugin_periodic_table"
repository = "https://github.com/JosephTLyons/nu_plugin_periodic_table"
version = "0.2.6"

[dependencies]
nu-ansi-term = "0.49.0"
nu-plugin = "0.85.0"
nu-protocol = "0.85.0"
indexmap = "2.0.2"
periodic-table-on-an-enum = "0.3.2"
